// Character code constants.
const int $BACKSPACE = 0x08;
const int $TAB = 0x09;
const int $NEWLINE = 0x0a; //  '\n'
const int $CARRIAGE_RETURN = 0x0d; // '\r'
const int $FORM_FEED = 0x0c; // '\f'
const int $SPACE = 0x20; // ' '
const int $DOUBLE_QUOTE = 0x22; // '"'
const int $DOLLAR = 0x24; // '$'
const int $SINGLE_QUOTE = 0x27; // '''
const int $WILDCARD = 0x2A; // '*'
const int $PLUS = 0x2b; // '+'
const int $COMMA = 0x2c; // ','
const int $MINUS = 0x2d; // '-'
const int $DOT = 0x2e; // '.'
const int $SLASH = 0x2f; // '/'
const int $CHAR_0 = 0x30;
const int $CHAR_1 = 0x31;
const int $CHAR_9 = 0x39;
const int $COLON = 0x3a; // ':'
const int $CHAR_A = 0x41;
const int $CHAR_Z = 0x5a;
const int $CHAR_E = 0x45;
const int $LBRACKET = 0x5b; // '['
const int $BACKSLASH = 0x5c; // '\'
const int $RBRACKET = 0x5d; // ']'
const int $UNDERLINE = 0x5f; // '_'
const int $CHAR_a = 0x61;
const int $CHAR_b = 0x62;
const int $CHAR_e = 0x65;
const int $CHAR_f = 0x66;
const int $CHAR_l = 0x6c;
const int $CHAR_n = 0x6e;
const int $CHAR_r = 0x72;
const int $CHAR_s = 0x73;
const int $CHAR_t = 0x74;
const int $CHAR_u = 0x75;
const int $CHAR_z = 0x7a;
const int $LBRACE = 0x7b; // '{'
const int $RBRACE = 0x7d; // '}'

const int $BEYOUND_ASCII = 0x80;
